import { Document, Font, Page, StyleSheet, Text, View } from '@react-pdf/renderer';

Font.register({
  family: 'Inter',
  fonts: [
    { src: 'https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZ9hiJ-Ek-_EeA.woff', fontWeight: 400 },
    { src: 'https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuGKYAZ9hiJ-Ek-_EeA.woff', fontWeight: 600 },
  ],
});

const styles = StyleSheet.create({
  page: { fontFamily: 'Inter', fontSize: 9, color: '#1a1a1a', padding: 48, backgroundColor: '#ffffff' },
  header: { marginBottom: 24, paddingBottom: 16, borderBottomWidth: 1, borderBottomColor: '#e5e7eb' },
  title: { fontSize: 14, fontWeight: 600, color: '#111827', marginBottom: 4 },
  subtitle: { fontSize: 9, color: '#6b7280' },
  disclaimer: { marginTop: 6, fontSize: 8, color: '#9ca3af' },
  item: { marginBottom: 16, paddingBottom: 16, borderBottomWidth: 1, borderBottomColor: '#f3f4f6' },
  clauseType: { fontSize: 8, fontWeight: 600, color: '#6b7280', textTransform: 'uppercase', letterSpacing: 0.8, marginBottom: 6 },
  label: { fontSize: 7.5, fontWeight: 600, color: '#374151', textTransform: 'uppercase', letterSpacing: 0.6, marginBottom: 3 },
  clauseBox: { backgroundColor: '#f9fafb', borderWidth: 1, borderColor: '#e5e7eb', borderRadius: 3, padding: 8, marginBottom: 8 },
  clauseText: { fontSize: 8.5, color: '#374151', lineHeight: 1.5 },
  proposedBox: { backgroundColor: '#f0fdf4', borderWidth: 1, borderColor: '#bbf7d0', borderRadius: 3, padding: 8, marginBottom: 8 },
  proposedText: { fontSize: 8.5, color: '#166534', lineHeight: 1.5 },
  rationaleText: { fontSize: 8, color: '#6b7280', fontStyle: 'italic', lineHeight: 1.4 },
  footer: { position: 'absolute', bottom: 32, left: 48, right: 48 },
  footerText: { fontSize: 7.5, color: '#d1d5db', textAlign: 'center' },
  pageNumber: { fontSize: 7.5, color: '#d1d5db', textAlign: 'right', marginTop: 2 },
});

type Item = { clauseType: string; clauseText: string; proposedText: string; explanation: string };

type Props = { items: Item[]; fileName: string; generatedAt: string };

export function MarkupSchedulePdf({ items, fileName, generatedAt }: Props) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Pactora Markup Schedule</Text>
          <Text style={styles.subtitle}>{fileName} — {generatedAt}</Text>
          <Text style={styles.disclaimer}>
            This document contains proposed language changes for negotiation purposes only. It does not constitute legal advice. Review all proposed changes with qualified legal counsel before sending to a counterparty.
          </Text>
        </View>

        {items.map((item, i) => (
          <View key={i} style={styles.item}>
            <Text style={styles.clauseType}>{item.clauseType}</Text>

            <Text style={styles.label}>Current wording</Text>
            <View style={styles.clauseBox}>
              <Text style={styles.clauseText}>{item.clauseText || 'Clause text not available'}</Text>
            </View>

            <Text style={styles.label}>Proposed wording</Text>
            <View style={styles.proposedBox}>
              <Text style={styles.proposedText}>{item.proposedText}</Text>
            </View>

            {item.explanation ? (
              <>
                <Text style={styles.label}>Rationale</Text>
                <Text style={styles.rationaleText}>{item.explanation}</Text>
              </>
            ) : null}
          </View>
        ))}

        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>Generated by Pactora · pactora.vercel.app</Text>
          <Text style={styles.pageNumber} render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
        </View>
      </Page>
    </Document>
  );
}
